# Generated by Django 4.1.7 on 2023-06-13 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_duration', models.DurationField()),
                ('time_of_day', models.TimeField()),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('ARTICLE', 'Article'), ('ADVERTISEMENT', 'Advertisement')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('reaction_to_ad', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
