# Generated by Django 5.1.4 on 2025-01-19 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
        migrations.AddField(
            model_name='address',
            name='geocoordinates',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='localisation_app.geocoordinates'),
            preserve_default=False,
        ),
    ]
