# Generated by Django 5.1.4 on 2025-01-15 14:03

import images_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0002_remove_album_owner_album_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=images_app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=images_app.models.user_directory_path),
        ),
    ]
