# Generated by Django 4.0.6 on 2022-07-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('titre', models.CharField(max_length=150)),
                ('categorie', models.CharField(max_length=150)),
                ('icon_petit', models.ImageField(max_length=150, upload_to='')),
                ('icon_grand', models.ImageField(max_length=150, upload_to='')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateMiseAJour', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
