# Generated by Django 4.1.7 on 2024-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='titre',
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_en',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_es',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_fr',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_ind',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_ita',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_jp',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_ko',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_pol',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_por',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='sport',
            name='sp_titre_ru',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='sport',
            name='categorie',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
