# Generated by Django 5.1.4 on 2025-03-10 22:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_remove_player_email_remove_player_first_name_and_more'),
        ('sport_app', '0002_remove_sport_titre_sport_sp_titre_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sports',
        ),
        migrations.AddField(
            model_name='player',
            name='frequence',
            field=models.CharField(blank=True, choices=[('OCC', 'Occasional'), ('REG', 'Regular'), ('INT', 'Intensive'), ('PRO', 'Professional'), ('OTH', 'Other')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.CharField(blank=True, choices=[('TB', 'True Beginner'), ('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('EXP', 'Expert'), ('PRO', 'Professional'), ('ELI', 'Elite'), ('WOC', 'World Class'), ('LEG', 'Legendary'), ('GDL', 'Godlike')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='niveau',
            field=models.IntegerField(default=3, help_text="Player's level from 0 to 10", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sport_app.sport'),
            preserve_default=False,
        ),
    ]
