# Generated by Django 4.1.7 on 2024-09-16 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicite_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_budget', models.CharField(choices=[('quotidien', 'Quotidien'), ('global', 'Global')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetEtCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('date_fin', models.DateField()),
                ('heure_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CampagnePublicitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_campagne', models.CharField(max_length=255)),
                ('type_achat', models.CharField(max_length=50)),
                ('objectif', models.CharField(max_length=100)),
                ('categories_speciales_a_ecarter', models.JSONField()),
                ('limite_depense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placement', models.CharField(max_length=255)),
                ('liste_publicite', models.JSONField()),
                ('statut_campagne', models.CharField(blank=True, max_length=50, null=True)),
                ('taux_clics', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nombre_impressions', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_campagne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publicite_app.budgetcampagne')),
                ('budget_et_calendrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publicite_app.budgetetcalendrier')),
            ],
        ),
        migrations.CreateModel(
            name='ControleAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=255)),
                ('age_minimum', models.IntegerField()),
                ('langues', models.JSONField()),
                ('centre_interet', models.JSONField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CtaButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('lien', models.URLField(max_length=500)),
                ('couleur', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('gif', 'GIF')], max_length=50)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('lien', models.URLField(max_length=500)),
                ('logo', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PubliciteBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_publicite', models.CharField(choices=[('video', 'Vidéo'), ('banniere', 'Bannière'), ('carrousel', 'Carrousel'), ('native', 'Native')], max_length=50)),
                ('nom_publicite', models.CharField(max_length=255)),
                ('texte_principal', models.TextField()),
                ('url_destination', models.URLField(blank=True, max_length=500, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('clics', models.IntegerField(blank=True, null=True)),
                ('taux_conversion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('campagne_publicitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicites', to='publicite_app.campagnepublicitaire')),
                ('cta_button', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicite_app.ctabutton')),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publicite_app.media')),
            ],
        ),
        migrations.RemoveField(
            model_name='adcampaign',
            name='owner',
        ),
        migrations.CreateModel(
            name='PubliciteBanniere',
            fields=[
                ('publicitebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicite_app.publicitebase')),
                ('emplacement_banniere', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=50)),
            ],
            bases=('publicite_app.publicitebase',),
        ),
        migrations.CreateModel(
            name='PubliciteCarrousel',
            fields=[
                ('publicitebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicite_app.publicitebase')),
                ('liste_images', models.ManyToManyField(to='publicite_app.media')),
            ],
            bases=('publicite_app.publicitebase',),
        ),
        migrations.CreateModel(
            name='PubliciteNative',
            fields=[
                ('publicitebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicite_app.publicitebase')),
                ('source', models.CharField(max_length=255)),
            ],
            bases=('publicite_app.publicitebase',),
        ),
        migrations.CreateModel(
            name='PubliciteVideo',
            fields=[
                ('publicitebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicite_app.publicitebase')),
                ('video_autoplay', models.BooleanField(default=True)),
                ('video_muted', models.BooleanField(default=False)),
            ],
            bases=('publicite_app.publicitebase',),
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='AdCampaign',
        ),
        migrations.AddField(
            model_name='campagnepublicitaire',
            name='controle_audience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publicite_app.controleaudience'),
        ),
        migrations.AddField(
            model_name='campagnepublicitaire',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campagnepublicitaire',
            name='page_facebook',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publicite_app.pagefacebook'),
        ),
    ]
