# Generated by Django 5.1.4 on 2025-02-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicite_app', '0002_budgetcampagne_budgetetcalendrier_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudgetEtCalendrier',
            new_name='Calendrier',
        ),
        migrations.RenameField(
            model_name='campagnepublicitaire',
            old_name='budget_et_calendrier',
            new_name='calendrier',
        ),
        migrations.AddField(
            model_name='controleaudience',
            name='age_maximum',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicitebase',
            name='ordreAffichage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
