# Generated by Django 5.1.4 on 2025-01-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Player', '0002_remove_player_email_remove_player_first_name_and_more'),
        ('localisation_app', '0002_geocoordinates_remove_address_latitude_and_more'),
        ('sport_app', '0002_remove_sport_titre_sport_sp_titre_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('is_preferred', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'En attente'), ('Accepted', 'Acceptée'), ('Declined', 'Refusée'), ('Cancelled', 'Annulée'), ('Expired', 'Expirée')], default='Pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('has_players_met_before', models.BooleanField(default=False)),
                ('alternative_locations', models.ManyToManyField(blank=True, related_name='alternative_invitations', to='localisation_app.address')),
                ('confirmed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_invitations', to='localisation_app.address')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='Player.player')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='Player.player')),
                ('proposed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_invitations', to='localisation_app.address')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_app.sport')),
                ('proposed_dates', models.ManyToManyField(blank=True, to='invitation_app.proposeddate')),
            ],
        ),
        migrations.CreateModel(
            name='InvitationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='invitation_app.invitation')),
            ],
        ),
    ]
