# Generated by Django 4.1.7 on 2024-09-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0002_remove_sport_titre_sport_sp_titre_en_and_more'),
        ('invitation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='sport_app.sport'),
        ),
    ]
