# Generated by Django 5.1.4 on 2025-01-09 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0003_invitation_invitation_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProposedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('is_preferred', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('popularity_rank', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='date',
            new_name='confirmed_date',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='created_at',
            new_name='invitation_date',
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invitation',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='has_players_met_before',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Pending', 'En attente'), ('Accepted', 'Acceptée'), ('Declined', 'Refusée'), ('Cancelled', 'Annulée'), ('Expired', 'Expirée')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InvitationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='invitation_app.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_indoor', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('coordinates', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitation_app.geocoordinates')),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='alternative_locations',
            field=models.ManyToManyField(blank=True, related_name='alternative_invitations', to='invitation_app.location'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='confirmed_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_invitations', to='invitation_app.location'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='proposed_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_invitations', to='invitation_app.location'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='player_a',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='invitation_app.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='player_b',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='invitation_app.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='proposed_dates',
            field=models.ManyToManyField(blank=True, to='invitation_app.proposeddate'),
        ),
        migrations.AddField(
            model_name='player',
            name='sports',
            field=models.ManyToManyField(related_name='players', to='invitation_app.sport'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='invitation_app.sport'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invitation_chat',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='updated_at',
        ),
    ]
