# Generated by Django 5.1.4 on 2025-01-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_remove_profileuser_adresse_profileuser_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='friends',
        ),
    ]
