# Generated by Django 5.1.4 on 2025-02-08 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0003_alter_album_cover_image_alter_photo_image'),
        ('profile_app', '0003_remove_profileuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='albums_photo',
            field=models.ManyToManyField(blank=True, related_name='profile_users', to='images_app.album'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
