# Generated by Django 5.1.4 on 2025-02-08 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_remove_profileuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='profile_image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='cover_image',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='profileuser',
            old_name='birth_date',
            new_name='birthday',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='location',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileuser',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
