# Generated by Django 4.1.7 on 2024-09-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0001_initial'),
        ('sport_events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='sportFK',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sport_events', to='sport_app.sport'),
            preserve_default=False,
        ),
    ]
