# Generated by Django 5.1.4 on 2025-01-19 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation_app', '0002_geocoordinates_remove_address_latitude_and_more'),
        ('sport_events_app', '0003_geocoordinates_mediacoverage_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='coordinates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_events', to='localisation_app.geocoordinates'),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='localisation_app.geocoordinates'),
        ),
        migrations.DeleteModel(
            name='GeoCoordinates',
        ),
    ]
