# Generated by Django 5.1.4 on 2025-01-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation_app', '0002_geocoordinates_remove_address_latitude_and_more'),
        ('sport_events_app', '0004_alter_sportevent_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='coordinates',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localisation_app.address'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_events', to='localisation_app.address'),
        ),
    ]
