# Generated by Django 5.1.4 on 2025-01-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_events_app', '0005_remove_location_coordinates_alter_location_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportevent',
            old_name='coordinates',
            new_name='adresse',
        ),
    ]
