# Generated by Django 5.1.4 on 2025-01-19 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisation_app', '0002_geocoordinates_remove_address_latitude_and_more'),
        ('sport_events_app', '0006_rename_coordinates_sportevent_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_events', to='localisation_app.address'),
        ),
    ]
